Cache - a memory- or time-limited dictionary type.
Cache instances work just like ordinary python dictionaries, with one
exception: They can forget things without you explicitly asking them
to.

This is likely to be useful for e.g. re-using the driver-specific SQL
equivalent of a compatibility-item-containing SQL statement, thus
reducing the time spent on compatibility item translation.