Corrected inheritance order for class OU, to make the code work with Python >= 2.3; when Entity appears before EntityQuarantine (which is a subclass of Entity), Python 2.3 won't stand for it, and raises this exception:
  TypeError: Cannot create a consistent method resolution
  order (MRO) for bases EntityQuarantine, Entity

Apart from avoiding this exception, the corrected order (where Entity
appears after all its subclasses) seems much more likely to do the
right thing; if EntityQuarantine overrides some method of Entity, it
is likely that a subclass of EntityQuarantine (and hence Entity) would
want to use the method appearing in EntityQuarantine rather than the
one from Entity.