new command, EMAIL REASSIGN_ADDRESS, allows an address to be moved from one account to the other, as long as they have the same owner.
if you have access to EMAIL REMOVE_ADDRESS on the address, you're allowed
to reassign it, as well.

the person himself/herself can manipulate his/her addresses.  examples
run as the unpriveleged test user tenghil:

jbofh> email reassign_address k.t.homme@usit.uio.no test1040
Error: CerebrumError: Can't reassign e-mail address to deleted account test1040
jbofh> email reassign_address k.t.homme@usit.uio.no zzkjhg
OK
jbofh> email reassign_address k.t.homme@usit.uio.no hm
Error: CerebrumError: Can't reassign e-mail address to a different person.
jbofh> email reassign_address ernstgr@snf.uio.no ernst
Error: PermissionDenied: No access to disk