Tell in what mixin a class couldn't be found
Up until now, the exception message is::

    AttributeError: type object 'module' has no attribute 'Constants'

which makes you search through all mixins in cereconf, if you're not familiar
with recent changes. This commit changes it to::

    ImportError: Module 'Cerebrum.modules.no.uio.bofhd_auth' has no class 'Constants'

HTH